from . import property_detail
from . import property_tag
from . import property_service
from . import property_utility_service
from . import property_document
from . import property_specification
from . import property_amenity
from . import property_image
from . import property_floorplan
from . import property_connectivity
from . import property_project
from . import property_sub_project
from . import sale_contract
from . import rent_contract
from . import rent_installment
from . import maintenance_request
from . import crm_lead
from . import property_broker_history
from . import property_section
from . import property_area_measurement
from . import account_move
from . import property_payment_term
from . import property_residential_type
from . import res_config_settings
# from . import
