{
    "name": "Property Sale & Rental Management",
    "version": "1.4.1",
    "category": "Extra Tools, Industries",
    "summary": "The Real Estate Management App is an all-in-one solution for managing properties, projects, rentals, and sales. property management property management system real estate management real estate CRM software rental property management lease management tenant management property maintenance property accounting rent collection property inspections tenant onboarding tenant portal property documents rental agreements lease contracts property operations building management asset management residential property management commercial property management facilities management property unit management rental tracking tenant communication maintenance requests work order management property billing utility management property tax tracking occupancy management vacancy management rent schedule rent reminders property expense tracking owner statements property reporting property dashboard property automation rental workflow lease renewal tenant deposit tracking rental notices property compliance room management property portfolio management property performance analysis multi-property management rent forecasting tenant ledger property income tracking property payment management maintenance scheduling service provider management rental dispute management predictive maintenance property analytics property insights property forecasting occupancy analytics advanced rental operations performance management multi-building management real estate automation property task automation dynamic rent scheduling document automation compliance tracking integrated utility billing IoT property monitoring remote property monitoring asset lifecycle management service request automation vendor management real-time maintenance tracking advanced property management advanced property accounting smart property dashboard business intelligence property rental behavior analytics automated lease renewal deposit management multi-owner property management centralized property reporting cloud-based property management multi-location property management tenant engagement tools workflow-driven property management cost optimization property advanced vacancy management smart alerts property automated notices contract lifecycle management rental installment management integrated CRM for property rental audit property controls property rental management property contract management real estate project tracking real estate invoice generator maintenance request tracker property listing and floor plan management real estate dashboard tenant and owner management real estate leasing software all-in-one property management digital real estate platform real estate ERP all in one property management advance property management all in one property property sell property rent property maintenance property agreement rental management base property management property auction building management project management Property Management sell and rental property contracts and calculate broker commission and many more Property Sale & Rental Management Property Sales Property Rental",
    "author": "INKERP",
    "website": "www.inkerp.com",
    "depends": [
        "crm",
        "contacts",
        "hr",
        "account",
        "maintenance",
        "website",
        "calendar",
        "helpdesk",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/data.xml",
        "data/master_data.xml",
        "data/property_inspection_checklist_data.xml",
        "reports/ir_action_report.xml",
        "reports/property_brochure_custom_report.xml",
        "reports/rent_contract_movein_permit_report.xml",
        "reports/rent_contract_movein_permit_template.xml",
        "reports/rent_contract_moveout_noc_report.xml",
        "reports/rent_contract_moveout_noc_template.xml",
        "reports/property_inspection_report.xml",
        "reports/property_inspection_template.xml",
        "views/property_detail_view.xml",
        "wizards/rent_contract_extend_wizard.xml",
        "wizards/rent_contract_report_view.xml",
        "wizards/rent_contract_full_report_view.xml",
        "views/property_tag_view.xml",
        "views/property_inspection_view.xml",
        "views/property_residential_type_view.xml",
        "views/property_payment_term_view.xml",
        "views/property_service_view.xml",
        "views/res_config_settings_view.xml",
        "views/property_project_view.xml",
        "views/property_sub_project_view.xml",
        "views/sale_contract_view.xml",
        "views/rent_contract_view.xml",
        "views/rent_contract_movein_view.xml",
        "views/rent_contract_moveout_view.xml",
        "views/property_section_view.xml",
        "views/crm_lead_view.xml",
        "views/helpdesk_ticket_view.xml",
        "views/account_move_view.xml",
        "reports/tenant_financial_statement_report.xml",
        "reports/tenant_financial_statement_template.xml",
    ],
    "demo": [
        "data/project_demo_data.xml",
        "data/property_demo_data.xml",
        "data/contract_demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "price": "49.0",
    "currency": "EUR",
    "license": "OPL-1",
    "images": [
        "static/description/banner.gif",
    ],
    "description": "The Real Estate Management App is an all-in-one solution for managing properties, projects, rentals, and sales. It helps automate rent and sale contracts, broker commissions, and financial reports. Users can easily handle maintenance requests, invoices, and property details like floor plans and amenities. The app also includes modules for managing customers, vendors, employees, and leads ensuring smooth operations across all departments. A perfect tool for property managers and real estate businesses to stay organized and efficient.",
}